services:
  actual-helpers:
    container_name: actual-helpers
    build: .
    volumes:
      - ./cache:/usr/src/app/cache
    restart: unless-stopped
    networks:
      - actual-budget

networks:
  actual-budget:
    name: actual-budget-network
    external: true