services:
  actual-helpers:
    container_name: actual-helpers
    build: .
    env_file: .env
    volumes:
      - ./cache:/usr/src/app/cache
    restart: unless-stopped
    networks:
      - actual-budget
      - eth-docker_default

networks:
  actual-budget:
    name: actual-budget-network
    external: true
  eth-docker_default:
    external: true
